### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by charles-esterbrook** [Virakal/SublimeCobra#1]
I'm using Sublime Text 3 build 3080. I installed the Cobra package per the ReadMe using the Package Control extension. I do see Cobra files in the packages directory:

```
~/Library/Application Support/Sublime Text 3  $  finder Cobra
./Cache/Cobra
./Cache/Cobra/Cobra.tmLanguage.cache
./Installed Packages/Cobra.sublime-package
```

However, I don't see any syntax highlighting. I have restarted Sublime.
Any ideas?

**Comment by Virakal** [comment]
Hey Charles,

I'm presuming the files have a .cobra extension? It should be set up for those by default.
Do you see `Cobra` under View > Syntax?

**Comment by charles-esterbrook** [comment]
I could have sworn that I checked that the syntax was set to Cobra, but maybe I just saw the extension and assumed. I think I checked that "Open all with current extension as..." was correct and it was.

In any case, explicitly picking the syntax works and it sticks between relaunches. Thanks!

**Comment by Virakal** [comment]
It's still odd that it wouldn't work out of the box. I'll see if I can reproduce it! Cheers.
